### PR TITLE
Add link to MATLAB's URDF primer

### PR DESCRIPTION
**Pull request by traversaro**
I think it is a useful link.

### CODE REVIEW

**Review by fabiodinatale — APPROVED** [review]
The modification to the `README.md` is fine, then it can be approved.
I think it was very useful to have added this entry point for *URDF* directly in the `README.md` rather than let the reader find himself in Matlab documentation.

Just a small comment on the last part of the `README.md` (independent from the approved modification). There is a duplicate sentence here:

>  - [Robotics StackExchange](https://robotics.stackexchange.com/?tags=urdf) - **Questions related to URDF in Robotics StackExchange**.
> - [ROS Answers](https://answers.ros.org/questions/scope%3Aall/sort%3Aactivity-desc/tags%3Aurdf/) - **Questions related to URDF in Robotics StackExchange**.

**Comment by traversaro** [comment]
@fabiodinatale yes, probably it make sense. Feel free to modify this PR (you should have the permisson) or propose a completly new modification with the new proposed location.

**Comment by fabiodinatale** [comment]
> Feel free to modify this PR (you should have the permisson) or propose a completly new modification with the new proposed location.

I think I corrected the duplicated sentence (actually, it was the description which was the same for the two points, while the locations, i.e. the links, were different and correct.

**Comment by traversaro** [comment]
Thanks @fabiodinatale ! Do you think we can merge the PR now?

**Comment by fabiodinatale** [comment]
> Thanks @fabiodinatale ! Do you think we can merge the PR now?

Yes! @traversaro

**Pull request merged**
